---
- name: Install Docker
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - { role: docker_ubuntu, when: "ansible_distribution == 'Ubuntu'"}
    - { role: docker_centos, when: "ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'"}