---
      
  - name: Extra Packages for Trusty 14.04
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    with_items:
      - linux-image-extra-$(uname -r)
      - linux-image-extra-virtual
    when: ansible_distribution_version|version_compare('14.04','=')  
    
  - name: Install packages to allow apt to use a repository over HTTPS
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
     
  - name: Add Docker official GPG key
    apt_key:
      id: "{{apt_key_id}}"
      keyserver: "{{apt_key_keyserver}}"
      state: present
      
  - name: Add Docker repository
    apt_repository:
      repo: deb https://apt.dockerproject.org/repo {{ ansible_lsb.id|lower }}-{{ ansible_lsb.codename|lower }} main
      state: present
      update_cache: yes

  - name: Install Docker package
    apt:
      update_cache: yes
      name: docker-engine
      state: latest
      
  - name: Docker Daemon Running
    service:
      name: docker
      state: started
      
      
      
   
